- hosts: all
  become: yes
  become_user: root
  roles:
    - role: common-my
    - role: langs
    - role: web-bootstrap-myDB2
    - role: web-go
#     - role: web-node
#     - role: web-ruby
#     - role: web-rust
#     - role: web-deno
#     - role: web-php
#     - role: web-perl
#     - role: web-python
    - role: web-prepare
    # - role: remove
