---
repository: https://github.com/isucon10-qualify/isucon10-qualify.git
kernel:
  - { param: 'fs.file-max', value: '655360' }
  - { param: 'net.core.somaxconn', value: '65535' }
  - { param: 'net.core.netdev_max_backlog', value: '65535' }
  - { param: 'net.ipv4.tcp_max_tw_buckets', value: '65535' }
  - { param: 'net.ipv4.tcp_max_syn_backlog', value: '65535' }
  - { param: 'net.ipv4.tcp_tw_reuse', value: '1' }
  - { param: 'net.ipv4.tcp_syn_retries', value: '3' }
  - { param: 'net.ipv4.tcp_fin_timeout', value: '10' }
  - { param: 'net.ipv4.tcp_rfc1337', value: '1' }
  - { param: 'vm.swappiness', value: '10' }
